### ISSUE TITLE
No such file or directory, open './github_markup.html'

### ISSUE THREAD

**Issue by lewiscowper** [npm/marky-compare#3]
<img width="771" alt="screen shot 2016-11-03 at 20 33 00" src="https://cloud.githubusercontent.com/assets/593574/19982064/cbc44f0a-a204-11e6-923a-39cc20776d44.png">

```
fs.js:557
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open './github_markup.html'
  at Object.fs.openSync (fs.js:557:18)
  at Object.fs.readFileSync (fs.js:467:33)
  at diff_readmes (/Users/lewis/dev/marky-compare/index.js:56:19)
  at Request._callback (/Users/lewis/dev/marky-compare/index.js:18:5)
  at Request.self.callback (/Users/lewis/dev/marky-compare/node_modules/request/request.js:186:22)
  at emitTwo (events.js:106:13)
  at Request.emit (events.js:191:7)
  at Request.<anonymous> (/Users/lewis/dev/marky-compare/node_modules/request/request.js:1081:10)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:188:7)
  at IncomingMessage.<anonymous> (/Users/lewis/dev/marky-compare/node_modules/request/request.js:1001:12)
  at IncomingMessage.g (events.js:291:16)
  at emitNone (events.js:91:20)
  at IncomingMessage.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ashleygwilliams** [comment]
this should be fixed as of the latest commit! please reopen if you keep having issues :)
